---
# Site-wide playbook - Run all configurations using roles
# Usage: ansible-playbook site.yml --ask-become-pass --ask-vault-pass

- name: Configure system
  hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - vars/vault.yml

  roles:
    - role: homebrew
      tags: homebrew

    - role: nix
      tags: nix

    - role: wifi
      tags: wifi
