---
# Site-wide playbook - Run all configurations using roles
# Usage: ansible-playbook site.yml --ask-become-pass --ask-vault-pass

- name: Configure system
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: Load vault variables for WiFi
      ansible.builtin.include_vars:
        file: vars/vault.yml
      tags: wifi
      no_log: true

    - name: Run Homebrew role
      ansible.builtin.include_role:
        name: homebrew
      tags: homebrew

    - name: Run Nix role
      ansible.builtin.include_role:
        name: nix
      tags: nix

    - name: Run WiFi role
      ansible.builtin.include_role:
        name: wifi
      tags: wifi
