---
# Site-wide playbook - Run all configurations using roles
# Usage: ansible-playbook site.yml --ask-become-pass --ask-vault-pass

- name: Configure system
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: Load vault variables
      ansible.builtin.include_vars:
        file: vars/vault.yml
      tags:
        - wifi
        - tailscale
      no_log: true

    - name: Load NFS mounts
      ansible.builtin.include_vars:
        file: vars/nfs_mounts.yml
      tags: nfs

    - name: Load Syncthing configuration
      ansible.builtin.include_vars:
        file: vars/syncthing.yml
      tags: syncthing

    - name: Run Tailscale role
      ansible.builtin.import_role:
        name: tailscale
      tags: tailscale

    - name: Run Homebrew role
      ansible.builtin.import_role:
        name: homebrew
      tags: homebrew

    - name: Run Nix role
      ansible.builtin.import_role:
        name: nix
      tags: nix

    - name: Run NFS mounts role
      ansible.builtin.import_role:
        name: nfs
      tags: nfs

    - name: Run WiFi role
      ansible.builtin.import_role:
        name: wifi
      tags: wifi

    - name: Run Syncthing role
      ansible.builtin.import_role:
        name: syncthing
      tags: syncthing
